jetrobot:
  # Publish all joint states -----------------------------------
  joint_state_controller:
    type: joint_state_controller/JointStateController
    publish_rate: 50  

  # Position Controllers ---------------------------------------
  joint_leftwheel_position_controller:
    type: effort_controllers/JointPositionController
    joint: base_to_left_wheel
    pid: {p: 100.0, i: 0.01, d: 10.0}
  joint_rightwheel_position_controller:
    type: effort_controllers/JointPositionController
    joint: base_to_right_wheel
    pid: {p: 100.0, i: 0.01, d: 10.0}